"""Crossfade and pitch automation table for building the loops into FMOD.

Usage: python tools/pitch_table.py loops/2026-10-08

Each loop plays from the previous loop's rpm to the next loop's rpm on the `rpms`
parameter sheet: volume 0 -> 1 -> 0 (equal-power curve), pitch following
12 * log2(rpm / loop_rpm) semitones, so pitch is exactly right at every rpm. FMOD
interpolates automation linearly between points, so intermediate points are listed too.
Writes fmod_table.csv and FMOD_TABLE.md into the loops folder.
"""
import csv
import math
import sys
from pathlib import Path

RPM_MIN, RPM_MAX = 0, 7200     # the bottom loop holds down to 0, the top one up to here
STEPS = 4                      # automation points between neighbouring loops


def semitones(rpm, loop_rpm):
    return 12 * math.log2(max(rpm, 1) / loop_rpm)


def layer_points(rpms):
    """Per loop: list of (rpm, volume 0..1, pitch semitones) automation points."""
    out = []
    for i, r in enumerate(rpms):
        pts = []
        lo = rpms[i - 1] if i > 0 else None
        hi = rpms[i + 1] if i + 1 < len(rpms) else None
        if lo is None:
            pts.append((RPM_MIN, 1.0, semitones(rpms[0] * 0.75, r)))   # don't pitch below -5 st
        else:
            for k in range(STEPS + 1):
                p = lo + (r - lo) * k / STEPS
                pts.append((p, math.sin(math.pi / 2 * k / STEPS), semitones(p, r)))
        if hi is None:
            pts.append((RPM_MAX, 1.0, semitones(RPM_MAX, r)))
        else:
            for k in range(1, STEPS + 1):
                p = r + (hi - r) * k / STEPS
                pts.append((p, math.cos(math.pi / 2 * k / STEPS), semitones(p, r)))
        out.append(pts)
    return out


def main():
    d = Path(sys.argv[1])
    rows = [r for r in csv.DictReader(open(d / "manifest.csv")) if r["layer"] != "limiter"]
    table, md = [], ["# FMOD automation table", "",
                     "Volume uses an equal-power crossfade; pitch is in semitones. Enter the",
                     "points on each instrument's volume and pitch automation for the `rpms`",
                     "parameter. Generated by `tools/pitch_table.py` from `manifest.csv`.", ""]
    for layer in sorted({r["layer"] for r in rows}):
        loops = sorted((float(r["rpm"]), r["file"]) for r in rows if r["layer"] == layer)
        md += [f"## Layer `{layer}`", "", "| Loop | Plays from | Full at | Plays to | Pitch at start | Pitch at end |",
               "|---|---:|---:|---:|---:|---:|"]
        for (rpm, f), pts in zip(loops, layer_points([r for r, _ in loops])):
            for p, v, s in pts:
                table.append({"layer": layer, "loop": f, "loop_rpm": round(rpm, 1), "rpms": round(p),
                              "volume": round(v, 3), "pitch_st": round(s, 3)})
            md.append(f"| `{f}` | {pts[0][0]:.0f} | {rpm:.0f} | {pts[-1][0]:.0f} | "
                      f"{pts[0][2]:+.2f} st | {pts[-1][2]:+.2f} st |")
        md.append("")
    with open(d / "fmod_table.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(table[0]))
        w.writeheader()
        w.writerows(table)
    (d / "FMOD_TABLE.md").write_text("\n".join(md))
    print(f"{len(table)} automation points -> {d / 'fmod_table.csv'}")


if __name__ == "__main__":
    main()
